# Generated by Django 5.2.6 on 2025-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
